#!/bin/sh

TOOL_NAME=checkenv
REPO_BASE=$(git rev-parse --show-toplevel)
BIN_PATH="$REPO_BASE/bin"

ln -sf "$REPO_BASE/$TOOL_NAME/$TOOL_NAME" "$BIN_PATH/$TOOL_NAME" && echo "installed $TOOL_NAME" || echo "failed to install $TOOL_NAME"
